[environment]
install = ''  # use this location instead of hardcoding absolute paths
debug = false

[gpio]
relay1 = 0  # extend
relay2 = 0  # retract
switch1 = 0  # extend limit
switch2 = 0  # retract limit
switch3 = 0  # block
aux_switch1 = 0  # extend
aux_switch2 = 0  # retract

[properties]
max_tavel_time = 10
anvil_id = ''
