[environment]
debug = false

[gpio]
relay1 = 0
relay2 = 0
switch1 = 0
switch2 = 0
switch3 = 0
aux_switch1 = 0
aux_switch2 = 0

[properties]
timezone = ''
longitude = 0.0
latitude = 0.0
max_travel_time = 0
anvil_id = ''