[environment]
install = ''  # use this location instead of hardcoding absolute paths
debug = false

[gpio]
relay1 = 0  # extend
relay2 = 0  # retract
switch1 = 0  # extend limit
switch2 = 0  # retract limit
switch3 = 0  # block
aux_switch1 = 0  # relay1
aux_switch2 = 0  # relay2

[properties]
time_zone = ''
longitude = 0.0
latitude = 0.0
max_travel_time = 10
anvil_id = ''
