# Generated by Django 4.2 on 2023-04-07 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StartupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automation', models.BooleanField(default=False)),
                ('sunrise_offset', models.IntegerField(default=0)),
                ('sunset_offset', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_login', models.BooleanField(default=False, editable=False)),
                ('board_mode', models.CharField(default='BCM', editable=False, help_text='This is the help text for board_mode', max_length=5)),
                ('relay1', models.IntegerField(default=26, help_text='This is the help text for relay1', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)])),
                ('relay2', models.IntegerField(default=20, help_text='This is the help text for relay2', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)])),
                ('switch1', models.IntegerField(default=6, help_text='This is the help text for switch1', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)])),
                ('switch2', models.IntegerField(default=13, help_text='This is the help text for switch2', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)])),
                ('switch3', models.IntegerField(default=19, help_text='This is the help text for switch3', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)])),
                ('switch4', models.IntegerField(default=23, help_text='This is the help text for switch4', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)])),
                ('switch5', models.IntegerField(default=24, help_text='This is the help text for switch5', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)])),
                ('off_state', models.BooleanField(default=True, help_text='This is the help text for off_state')),
                ('timezone', models.CharField(default='US/Eastern', help_text='This is the help text for timezone', max_length=100)),
                ('longitude', models.DecimalField(decimal_places=6, default=0.0, help_text='This is the help text for longitude', max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, default=0.0, help_text='This is the help text for latitude', max_digits=9)),
                ('travel_time', models.IntegerField(default=10, help_text='This is the help text for travel_time')),
            ],
            options={
                'verbose_name': 'Startup Config',
                'verbose_name_plural': 'Startup Configs',
            },
        ),
    ]
