# Generated by Django 4.2 on 2023-04-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfig',
            name='first_login',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
