# Generated by Django 4.2 on 2023-04-07 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0002_alter_systemconfig_first_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemconfig',
            name='first_login',
        ),
    ]
