# Generated by Django 4.2 on 2023-04-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0003_remove_systemconfig_first_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfig',
            name='off_state',
            field=models.CharField(choices=[('True', 'On'), ('False', 'Off')], default='True', help_text='This is the help text for off_state', max_length=5),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='timezone',
            field=models.CharField(help_text='This is the help text for timezone', max_length=100),
        ),
    ]
