# Generated by Django 4.2 on 2023-04-07 20:01

import controls.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0004_alter_systemconfig_off_state_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemconfig',
            options={'verbose_name': 'System Config', 'verbose_name_plural': 'System Configs'},
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='relay1',
            field=models.IntegerField(default=26, help_text='This is the help text for relay1', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31), controls.validators.excluded_pin]),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='relay2',
            field=models.IntegerField(default=20, help_text='This is the help text for relay2', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31), controls.validators.excluded_pin]),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='switch1',
            field=models.IntegerField(default=6, help_text='This is the help text for switch1', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31), controls.validators.excluded_pin]),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='switch2',
            field=models.IntegerField(default=13, help_text='This is the help text for switch2', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31), controls.validators.excluded_pin]),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='switch3',
            field=models.IntegerField(default=19, help_text='This is the help text for switch3', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31), controls.validators.excluded_pin]),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='switch4',
            field=models.IntegerField(default=23, help_text='This is the help text for switch4', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31), controls.validators.excluded_pin]),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='switch5',
            field=models.IntegerField(default=24, help_text='This is the help text for switch5', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31), controls.validators.excluded_pin]),
        ),
    ]
