# Generated by Django 4.2 on 2023-04-15 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0005_alter_systemconfig_options_alter_systemconfig_relay1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='startupconfig',
            options={'verbose_name': 'Automation', 'verbose_name_plural': 'Automations'},
        ),
        migrations.AddField(
            model_name='startupconfig',
            name='auxillary',
            field=models.BooleanField(default=False),
        ),
    ]
