# Generated by Django 4.2 on 2023-04-22 22:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0007_alter_startupconfig_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfig',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, help_text='Latitudinal location of hardware', max_digits=9, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, help_text='Longitudinal location of hardware', max_digits=9, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='off_state',
            field=models.CharField(choices=[('True', 'On'), ('False', 'Off')], default='True', help_text='Power setting of relay off state', max_length=5, verbose_name='Off State'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='relay1',
            field=models.IntegerField(default=26, help_text='Extending Motion', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)], verbose_name='Relay 1'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='relay2',
            field=models.IntegerField(default=20, help_text='Retraction Motion', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)], verbose_name='Relay 2'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='switch1',
            field=models.IntegerField(default=6, help_text='Extend Limit', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)], verbose_name='Switch 1'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='switch2',
            field=models.IntegerField(default=13, help_text='Retract Limit', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)], verbose_name='Switch 2'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='switch3',
            field=models.IntegerField(default=19, help_text='Door path is blocked', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)], verbose_name='Switch 3'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='switch4',
            field=models.IntegerField(default=23, help_text="Aux switch for 'Relay 1'", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)], verbose_name='Switch 4'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='switch5',
            field=models.IntegerField(default=24, help_text="Aux switch for 'Relay 2'", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)], verbose_name='Switch 5'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='timezone',
            field=models.CharField(help_text='Timezone of hardware', max_length=100, verbose_name='Timezone'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='travel_time',
            field=models.IntegerField(default=10, help_text='Allowed time, in seconds, for the door to be in motion', verbose_name='Travel Time'),
        ),
    ]
