# Generated by Django 4.2.1 on 2023-05-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0008_alter_systemconfig_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startupconfig',
            name='auxillary',
        ),
        migrations.AddField(
            model_name='startupconfig',
            name='auxiliary',
            field=models.BooleanField(default=False, help_text='Toggle auxiliary on or off', verbose_name='Auxiliary'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='board_mode',
            field=models.CharField(choices=[('BCM', 'BCM'), ('BOARD', 'BOARD')], default='BCM', help_text='GPIO pin numbering mode', max_length=5, verbose_name='Board Mode'),
        ),
    ]
