# Generated by Django 4.2.1 on 2023-05-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0008_alter_systemconfig_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfig',
            name='board_mode',
            field=models.CharField(choices=[('BCM', 'BCM'), ('BOARD', 'BOARD')], default='BCM', help_text='GPIO pin numbering mode', max_length=5, verbose_name='Board Mode'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='off_state',
            field=models.BooleanField(choices=[('True', 'On'), ('False', 'Off')], default='True', help_text='Power setting for relay off state', verbose_name='Off State'),
        ),
    ]
