# Generated by Django 4.2 on 2023-09-01 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0009_alter_systemconfig_board_mode_and_more'),
        ('controls', '0009_remove_startupconfig_auxillary_and_more'),
    ]

    operations = [
    ]
